name: "Build and Release Typst Presentation"

on:
  push:
    tags:
      - "*"

jobs:
  build-and-release:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v26

      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - name: Build with Typst
        shell: devenv shell bash -- -e {0}
        run: typst compile main.typ main.pdf

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

